// Semantic icon aliases for the Pludux GUI, backed by the Lucide icon font
// (via IconFontCppHeaders). Keeping the mapping in one place means the
// underlying icon set can change without touching call sites.
#pragma once

#include <IconsLucide.h>

#define PLUDUX_ICON_FONT_FILE_NAME FONT_ICON_FILE_NAME_LC
#define PLUDUX_ICON_MIN ICON_MIN_LC
#define PLUDUX_ICON_MAX_16 ICON_MAX_16_LC

// Actions
#define PLUDUX_ICON_ADD ICON_LC_PLUS
#define PLUDUX_ICON_DELETE ICON_LC_TRASH_2
#define PLUDUX_ICON_SEARCH ICON_LC_SEARCH
#define PLUDUX_ICON_HELP ICON_LC_CIRCLE_HELP
#define PLUDUX_ICON_WARNING ICON_LC_TRIANGLE_ALERT
#define PLUDUX_ICON_BACK ICON_LC_ARROW_LEFT
#define PLUDUX_ICON_COPY ICON_LC_COPY
#define PLUDUX_ICON_EDIT ICON_LC_PENCIL
#define PLUDUX_ICON_EXPORT ICON_LC_DOWNLOAD
#define PLUDUX_ICON_IMPORT ICON_LC_UPLOAD
#define PLUDUX_ICON_MORE ICON_LC_ELLIPSIS
#define PLUDUX_ICON_SAVE ICON_LC_SAVE
#define PLUDUX_ICON_UNDO ICON_LC_UNDO_2
#define PLUDUX_ICON_REDO ICON_LC_REDO_2
#define PLUDUX_ICON_RESET ICON_LC_ROTATE_CCW
#define PLUDUX_ICON_INFO ICON_LC_INFO

// Reordering / disclosure
#define PLUDUX_ICON_MOVE_UP ICON_LC_ARROW_UP
#define PLUDUX_ICON_MOVE_DOWN ICON_LC_ARROW_DOWN
#define PLUDUX_ICON_CHEVRON_UP ICON_LC_CHEVRON_UP
#define PLUDUX_ICON_CHEVRON_DOWN ICON_LC_CHEVRON_DOWN

// Series/indicator node categories
#define PLUDUX_ICON_CATEGORY_PRICE_VOLUME ICON_LC_CANDLESTICK_CHART
#define PLUDUX_ICON_CATEGORY_TREND ICON_LC_TRENDING_UP
#define PLUDUX_ICON_CATEGORY_MOMENTUM ICON_LC_ACTIVITY
#define PLUDUX_ICON_CATEGORY_VOLATILITY ICON_LC_WAVES
#define PLUDUX_ICON_CATEGORY_POSITION_RISK ICON_LC_SHIELD
#define PLUDUX_ICON_CATEGORY_LOGIC_MATH ICON_LC_SIGMA
#define PLUDUX_ICON_CATEGORY_INPUT_CUSTOM ICON_LC_VARIABLE

// Condition node categories
#define PLUDUX_ICON_CATEGORY_COMPARISON ICON_LC_EQUAL
#define PLUDUX_ICON_CATEGORY_CROSSOVER ICON_LC_ARROW_UP_DOWN
#define PLUDUX_ICON_CATEGORY_LOGIC ICON_LC_SIGMA
#define PLUDUX_ICON_CATEGORY_FIXED ICON_LC_TOGGLE_RIGHT
